;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65816"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "_afailed.c", 235, 959521248
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdio.h", 5951, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stddef.h", 2972, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdarg.h", 2817, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdlib.h", 5606, 1344797532
	.dbg		sym, "stderr", "00", extern, "_stderr"
	.dbg		sym, "fprintf", "00", extern, "_fprintf"
	.dbg		sym, "exit", "00", extern, "_exit"
	.import		_stderr
	.import		_fprintf
	.import		_exit
	.export		__afailed

.segment	"RODATA"

L0004:
	.byte	$41,$53,$53,$45,$52,$54,$49,$4F,$4E,$20,$46,$41,$49,$4C,$45,$44
	.byte	$20,$49,$4E,$20,$25,$73,$28,$25,$75,$29,$0A,$00

; ---------------------------------------------------------------
; void __near__ _afailed (__near__ unsigned char*, unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__afailed: near

	.dbg	func, "_afailed", "00", extern, "__afailed"
	.dbg	sym, "file", "00", auto, 2
	.dbg	sym, "line", "00", auto, 0

.segment	"CODE"

;
; fprintf (stderr, "ASSERTION FAILED IN %s(%u)\n", file, line);
;
	.dbg	line, "_afailed.c", 16
	jsr     decsp4
	lda     _stderr
	ldy     #$02
	sta     (sp),y
	iny
	lda     _stderr+1
	sta     (sp),y
	lda     #<(L0004)
	sta     (sp)
	ldy     #$01
	lda     #>(L0004)
	sta     (sp),y
	ldy     #$09
	jsr     pushwysp
	ldy     #$09
	jsr     pushwysp
	ldy     #$08
	jsr     _fprintf
;
; exit (2);
;
	.dbg	line, "_afailed.c", 17
	ldx     #$00
	lda     #$02
	jsr     _exit
;
; }
;
	.dbg	line, "_afailed.c", 18
	jmp     incsp4
	.dbg	line

.endproc

