;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65816"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "_poserror.c", 2961, 1051217755
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdio.h", 5951, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stddef.h", 2972, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdarg.h", 2817, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/string.h", 4883, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/errno.h", 4695, 1344797532
	.dbg		sym, "stderr", "00", extern, "_stderr"
	.dbg		sym, "fprintf", "00", extern, "_fprintf"
	.dbg		sym, "_stroserror", "00", extern, "__stroserror"
	.dbg		sym, "_oserror", "00", extern, "__oserror"
	.import		_stderr
	.import		_fprintf
	.export		__poserror
	.import		__stroserror
	.import		__oserror

.segment	"RODATA"

L0008:
	.byte	$25,$73,$3A,$20,$25,$73,$0A,$00
L000F	:=	L0008+4

; ---------------------------------------------------------------
; void __near__ __fastcall__ _poserror (__near__ const unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__poserror: near

	.dbg	func, "_poserror", "00", extern, "__poserror"
	.dbg	sym, "msg", "00", auto, 0
	.dbg	sym, "errormsg", "00", auto, -2

.segment	"CODE"

;
; {
;
	.dbg	line, "_poserror.c", 43
	jsr     pushax
;
; const char* errormsg = _stroserror (_oserror);
;
	.dbg	line, "_poserror.c", 45
	lda     __oserror
	jsr     __stroserror
	jsr     pushax
;
; if (msg) {
;
	.dbg	line, "_poserror.c", 48
	ldy     #$03
	lda     (sp),y
	dey
	ora     (sp),y
	beq     L0004
;
; fprintf (stderr, "%s: %s\n", msg, errormsg);
;
	.dbg	line, "_poserror.c", 49
	jsr     decsp4
	lda     _stderr
	sta     (sp),y
	iny
	lda     _stderr+1
	sta     (sp),y
	lda     #<(L0008)
	sta     (sp)
	ldy     #$01
	lda     #>(L0008)
	sta     (sp),y
	ldy     #$09
	jsr     pushwysp
	ldy     #$09
	jsr     pushwysp
	ldy     #$08
;
; } else {
;
	.dbg	line, "_poserror.c", 50
	bra     L0012
;
; fprintf (stderr, "%s\n", errormsg);
;
	.dbg	line, "_poserror.c", 51
L0004:	jsr     decsp4
	lda     _stderr
	sta     (sp),y
	iny
	lda     _stderr+1
	sta     (sp),y
	lda     #<(L000F)
	sta     (sp)
	ldy     #$01
	lda     #>(L000F)
	sta     (sp),y
	ldy     #$07
	jsr     pushwysp
	ldy     #$06
L0012:	jsr     _fprintf
;
; }
;
	.dbg	line, "_poserror.c", 53
	jmp     incsp4
	.dbg	line

.endproc

