;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65816"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "abort.c", 238, 1047600151
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdio.h", 5951, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stddef.h", 2972, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdarg.h", 2817, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdlib.h", 5606, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/signal.h", 3341, 1344797532
	.dbg		sym, "stderr", "00", extern, "_stderr"
	.dbg		sym, "fputs", "00", extern, "_fputs"
	.dbg		sym, "exit", "00", extern, "_exit"
	.dbg		sym, "raise", "00", extern, "_raise"
	.import		_stderr
	.import		_fputs
	.export		_abort
	.import		_exit
	.import		_raise

.segment	"RODATA"

L0005:
	.byte	$41,$42,$4E,$4F,$52,$4D,$41,$4C,$20,$50,$52,$4F,$47,$52,$41,$4D
	.byte	$20,$54,$45,$52,$4D,$49,$4E,$41,$54,$49,$4F,$4E,$0A,$00

; ---------------------------------------------------------------
; void __near__ abort (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_abort: near

	.dbg	func, "abort", "00", extern, "_abort"

.segment	"CODE"

;
; raise (SIGABRT);
;
	.dbg	line, "abort.c", 17
	ldx     #$00
	txa
	jsr     _raise
;
; fputs ("ABNORMAL PROGRAM TERMINATION\n", stderr);
;
	.dbg	line, "abort.c", 18
	lda     #<(L0005)
	ldx     #>(L0005)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
;
; exit (3);
;
	.dbg	line, "abort.c", 19
	ldx     #$00
	lda     #$03
	jmp     _exit
	.dbg	line

.endproc

