;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65816"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "asctime.c", 3053, 1037194125
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdio.h", 5951, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stddef.h", 2972, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdarg.h", 2817, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/time.h", 5015, 1344797532
	.dbg		sym, "strftime", "00", extern, "_strftime"
	.export		_asctime
	.import		_strftime

.segment	"RODATA"

L000A:
	.byte	$25,$63,$0A,$00

; ---------------------------------------------------------------
; __near__ unsigned char* __near__ __fastcall__ asctime (__near__ const struct tm*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_asctime: near

	.dbg	func, "asctime", "00", extern, "_asctime"
	.dbg	sym, "timep", "00", auto, 0

.segment	"BSS"

L0005:
	.res	26,$00

.segment	"CODE"

;
; {
;
	.dbg	line, "asctime.c", 48
	jsr     pushax
;
; return strftime (buf, sizeof (buf), "%c\n", timep)? buf : 0;
;
	.dbg	line, "asctime.c", 52
	jsr     decsp6
	lda     #<(L0005)
	ldy     #$04
	sta     (sp),y
	iny
	lda     #>(L0005)
	sta     (sp),y
	lda     #$1A
	ldy     #$02
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #<(L000A)
	sta     (sp)
	ldy     #$01
	lda     #>(L000A)
	sta     (sp),y
	ldy     #$07
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _strftime
	stx     tmp1
	ora     tmp1
	beq     L000D
	lda     #<(L0005)
	ldx     #>(L0005)
	jmp     incsp2
L000D:	tax
;
; }
;
	.dbg	line, "asctime.c", 53
	jmp     incsp2
	.dbg	line

.endproc

