;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65816"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "bsearch.c", 999, 1067464319
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdlib.h", 5606, 1344797532
	.export		_bsearch

; ---------------------------------------------------------------
; __near__ void* __near__ __fastcall__ bsearch (__near__ const void*, __near__ const void*, unsigned int, unsigned int, __near__ __near__ function returning int*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_bsearch: near

	.dbg	func, "bsearch", "00", extern, "_bsearch"
	.dbg	sym, "key", "00", auto, 8
	.dbg	sym, "base", "00", auto, 6
	.dbg	sym, "n", "00", auto, 4
	.dbg	sym, "size", "00", auto, 2
	.dbg	sym, "cmp", "00", auto, 0
	.dbg	sym, "current", "00", auto, -2
	.dbg	sym, "result", "00", auto, -4
	.dbg	sym, "found", "00", auto, -6
	.dbg	sym, "first", "00", auto, -8
	.dbg	sym, "last", "00", auto, -10

.segment	"CODE"

;
; {
;
	.dbg	line, "bsearch.c", 15
	jsr     pushax
;
; int found = 0;
;
	.dbg	line, "bsearch.c", 18
	jsr     decsp4
	jsr     push0
;
; int first = 0;
;
	.dbg	line, "bsearch.c", 19
	jsr     push0
;
; int last = n - 1;
;
	.dbg	line, "bsearch.c", 20
	ldy     #$0D
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sec
	sbc     #$01
	bcs     L0005
	dex
L0005:	jsr     pushax
;
; while (first <= last) {
;
	.dbg	line, "bsearch.c", 23
	jmp     L0008
;
; current = (last + first) / 2;
;
	.dbg	line, "bsearch.c", 26
L0006:	lda     (sp)
	ldy     #$02
	clc
	adc     (sp),y
	pha
	dey
	lda     (sp),y
	ldy     #$03
	adc     (sp),y
	tax
	pla
	jsr     asrax1
	ldy     #$08
	jsr     staxysp
;
; result = cmp ((void*) (((int) base) + current*size), key);
;
	.dbg	line, "bsearch.c", 29
	ldy     #$0D
	jsr     pushwysp
	jsr     decsp4
	ldy     #$19
	jsr     pushwysp
	ldy     #$13
	jsr     pushwysp
	ldy     #$17
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     tosumulax
	jsr     tosaddax
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$19
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     (sp)
	ldy     #$01
	txa
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     callax
	jsr     incsp2
	ldy     #$06
	jsr     staxysp
;
; if (result < 0) {
;
	.dbg	line, "bsearch.c", 30
	cpx     #$80
	bcc     L0013
;
; first = current + 1;
;
	.dbg	line, "bsearch.c", 31
	ldy     #$09
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ina
	bne     L0017
	inx
L0017:	ldy     #$02
	jsr     staxysp
;
; } else {
;
	.dbg	line, "bsearch.c", 32
	bra     L0008
;
; last = current - 1;
;
	.dbg	line, "bsearch.c", 33
L0013:	ldy     #$09
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sec
	sbc     #$01
	bcs     L001B
	dex
L001B:	jsr     stax0sp
;
; if (result == 0) {
;
	.dbg	line, "bsearch.c", 34
	ldy     #$06
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L0008
;
; found = 1;
;
	.dbg	line, "bsearch.c", 39
	ldy     #$04
	ina
	sta     (sp),y
	dea
	iny
	sta     (sp),y
;
; while (first <= last) {
;
	.dbg	line, "bsearch.c", 23
L0008:	ldy     #$05
	jsr     pushwysp
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     tosicmp
	jmi     L0006
	jeq     L0006
;
; return (void*) (found? ((int) base) + first*size : 0);
;
	.dbg	line, "bsearch.c", 45
	ldy     #$05
	lda     (sp),y
	dey
	ora     (sp),y
	beq     L0023
	ldy     #$13
	jsr     pushwysp
	ldy     #$07
	jsr     pushwysp
	ldy     #$11
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     tosumulax
	jsr     tosaddax
	bra     L0001
L0023:	tax
;
; }
;
	.dbg	line, "bsearch.c", 46
L0001:	ldy     #$14
	jmp     addysp
	.dbg	line

.endproc

