;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65816"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "fdopen.c", 750, 1068141847
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdio.h", 5951, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stddef.h", 2972, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdarg.h", 2817, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/fcntl.h", 3407, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/errno.h", 4695, 1344797532
	.dbg		file, "_file.h", 742, 1084367796
	.dbg		sym, "_errno", "00", extern, "__errno"
	.dbg		sym, "_fdesc", "00", extern, "__fdesc"
	.export		_fdopen
	.import		__errno
	.import		__fdesc

; ---------------------------------------------------------------
; __near__ struct _FILE* __near__ __fastcall__ fdopen (int, __near__ const unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fdopen: near

	.dbg	func, "fdopen", "00", extern, "_fdopen"
	.dbg	sym, "handle", "00", auto, 2
	.dbg	sym, "$anon-param-0001", "00", auto, 0
	.dbg	sym, "f", "00", auto, -2

.segment	"CODE"

;
; {
;
	.dbg	line, "fdopen.c", 23
	jsr     pushax
;
; if (!(f = _fdesc ())) {
;
	.dbg	line, "fdopen.c", 27
	jsr     decsp2
	jsr     __fdesc
	jsr     stax0sp
	stx     tmp1
	ora     tmp1
	bne     L0003
;
; _errno = EMFILE;            /* Too many files */
;
	.dbg	line, "fdopen.c", 29
	tax
	lda     #$05
	sta     __errno
	stz     __errno+1
;
; return 0;
;
	.dbg	line, "fdopen.c", 30
	txa
	jmp     incsp6
;
; f->f_fd    = handle;
;
	.dbg	line, "fdopen.c", 34
L0003:	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	lda     (sp)
	sta     ptr1
	ldy     #$04
	lda     (sp),y
	sta     (ptr1)
;
; f->f_flags = _FOPEN;
;
	.dbg	line, "fdopen.c", 35
	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	lda     (sp)
	sta     ptr1
	tya
	tay
	sta     (ptr1),y
;
; return f;
;
	.dbg	line, "fdopen.c", 38
	lda     (sp),y
	tax
	lda     (sp)
;
; }
;
	.dbg	line, "fdopen.c", 39
	jmp     incsp6
	.dbg	line

.endproc

