;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65816"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "fgetpos.c", 417, 1068141847
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdio.h", 5951, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stddef.h", 2972, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdarg.h", 2817, 1344797532
	.dbg		sym, "ftell", "00", extern, "_ftell"
	.export		_fgetpos
	.import		_ftell

; ---------------------------------------------------------------
; int __near__ __fastcall__ fgetpos (__near__ struct _FILE*, __near__ unsigned long*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fgetpos: near

	.dbg	func, "fgetpos", "00", extern, "_fgetpos"
	.dbg	sym, "f", "00", auto, 2
	.dbg	sym, "pos", "00", auto, 0

.segment	"CODE"

;
; {
;
	.dbg	line, "fgetpos.c", 20
	jsr     pushax
;
; *pos = ftell (f);
;
	.dbg	line, "fgetpos.c", 21
	jsr     pushw0sp
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _ftell
	ldy     #$00
	jsr     steaxspidx
;
; if (*pos != -1)
;
	.dbg	line, "fgetpos.c", 23
	ldy     #$01
	lda     (sp),y
	tax
	lda     (sp)
	jsr     ldeaxi
	jsr     pusheax
	ldx     #$FF
	stx     sreg
	stx     sreg+1
	txa
	jsr     tosneeax
	beq     L0005
;
; return 0;
;
	.dbg	line, "fgetpos.c", 24
	ldx     #$00
	txa
	jmp     incsp4
;
; return -1;
;
	.dbg	line, "fgetpos.c", 25
L0005:	ldx     #$FF
	txa
;
; }
;
	.dbg	line, "fgetpos.c", 26
	jmp     incsp4
	.dbg	line

.endproc

