;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65816"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "fgets.c", 1189, 1084483078
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdio.h", 5951, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stddef.h", 2972, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdarg.h", 2817, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/errno.h", 4695, 1344797532
	.dbg		file, "_file.h", 742, 1084367796
	.dbg		sym, "fgetc", "00", extern, "_fgetc"
	.dbg		sym, "_errno", "00", extern, "__errno"
	.import		_fgetc
	.export		_fgets
	.import		__errno

; ---------------------------------------------------------------
; __near__ unsigned char* __near__ __fastcall__ fgets (__near__ unsigned char*, unsigned int, __near__ struct _FILE*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fgets: near

	.dbg	func, "fgets", "00", extern, "_fgets"
	.dbg	sym, "s", "00", auto, 4
	.dbg	sym, "size", "00", auto, 2
	.dbg	sym, "f", "00", auto, 0
	.dbg	sym, "i", "00", auto, -2
	.dbg	sym, "c", "00", auto, -4

.segment	"CODE"

;
; {
;
	.dbg	line, "fgets.c", 22
	jsr     pushax
;
; if (size == 0) {
;
	.dbg	line, "fgets.c", 26
	jsr     decsp4
	ldy     #$06
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L0003
;
; _errno = EINVAL;
;
	.dbg	line, "fgets.c", 28
	tax
	sty     __errno
	stz     __errno+1
;
; return 0;
;
	.dbg	line, "fgets.c", 29
	txa
	jmp     L0002
;
; i = 0;
;
	.dbg	line, "fgets.c", 33
L0003:	ldx     #$00
	ldy     #$02
	txa
	sta     (sp),y
	iny
	sta     (sp),y
;
; while (--size) {
;
	.dbg	line, "fgets.c", 34
	jmp     L002C
;
; if ((c = fgetc (f)) == EOF) {
;
	.dbg	line, "fgets.c", 37
L000B:	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _fgetc
	jsr     stax0sp
	cpx     #$FF
	bne     L001F
	cmp     #$FF
	bne     L001F
;
; s[i] = '\0';
;
	.dbg	line, "fgets.c", 38
	ldy     #$08
	lda     (sp),y
	ldy     #$02
	clc
	adc     (sp),y
	sta     ptr1
	ldy     #$09
	lda     (sp),y
	ldy     #$03
	adc     (sp),y
	sta     ptr1+1
	lda     #$00
	sta     (ptr1)
;
; if ((f->f_flags & _FERROR) != 0 || i == 0) {
;
	.dbg	line, "fgets.c", 40
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$01
	lda     (ptr1),y
	and     #$04
	bne     L002B
	iny
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L000C
;
; return 0;
;
	.dbg	line, "fgets.c", 42
L002B:	inx
	txa
	bra     L0002
;
; s[i++] = c;
;
	.dbg	line, "fgets.c", 50
L001F:	ldy     #$0B
	jsr     pushwysp
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     regsave
	stx     regsave+1
	ina
	bne     L0022
	inx
L0022:	ldy     #$04
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	lda     (sp)
	sta     (ptr1)
;
; if (c == '\n') {
;
	.dbg	line, "fgets.c", 53
	ldy     #$01
	lda     (sp),y
	bne     L002D
	lda     (sp)
	cmp     #$0A
;
; break;
;
	.dbg	line, "fgets.c", 54
	beq     L000C
;
; while (--size) {
;
	.dbg	line, "fgets.c", 34
L002D:	ldx     #$00
L002C:	lda     #$01
	ldy     #$06
	jsr     subeqysp
	stx     tmp1
	ora     tmp1
	jne     L000B
;
; s[i] = '\0';
;
	.dbg	line, "fgets.c", 59
L000C:	ldy     #$08
	lda     (sp),y
	ldy     #$02
	clc
	adc     (sp),y
	sta     ptr1
	ldy     #$09
	lda     (sp),y
	ldy     #$03
	adc     (sp),y
	sta     ptr1+1
	lda     #$00
	sta     (ptr1)
;
; return s;
;
	.dbg	line, "fgets.c", 62
	ldy     #$09
	lda     (sp),y
	tax
	dey
	lda     (sp),y
;
; }
;
	.dbg	line, "fgets.c", 63
L0002:	ldy     #$0A
	jmp     addysp
	.dbg	line

.endproc

