;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65816"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "freopen.c", 878, 1068141847
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdio.h", 5951, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stddef.h", 2972, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdarg.h", 2817, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/fcntl.h", 3407, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/errno.h", 4695, 1344797532
	.dbg		file, "_file.h", 742, 1084367796
	.dbg		sym, "close", "00", extern, "_close"
	.dbg		sym, "_errno", "00", extern, "__errno"
	.dbg		sym, "_fopen", "00", extern, "__fopen"
	.export		_freopen
	.import		_close
	.import		__errno
	.import		__fopen

; ---------------------------------------------------------------
; __near__ struct _FILE* __near__ __fastcall__ freopen (__near__ const unsigned char*, __near__ const unsigned char*, __near__ struct _FILE*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_freopen: near

	.dbg	func, "freopen", "00", extern, "_freopen"
	.dbg	sym, "name", "00", auto, 4
	.dbg	sym, "mode", "00", auto, 2
	.dbg	sym, "f", "00", auto, 0

.segment	"CODE"

;
; {
;
	.dbg	line, "freopen.c", 23
	jsr     pushax
;
; if ((f->f_flags & _FOPEN) == 0) {
;
	.dbg	line, "freopen.c", 25
	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	lda     (sp)
	sta     ptr1
	ldy     #$01
	lda     (ptr1),y
	and     #$01
	bne     L0012
;
; _errno = EINVAL;  /* File not input */
;
	.dbg	line, "freopen.c", 27
	tax
	lda     #$07
	sta     __errno
	stz     __errno+1
;
; return 0;
;
	.dbg	line, "freopen.c", 28
	txa
	jmp     incsp6
;
; if (close (f->f_fd) < 0) {
;
	.dbg	line, "freopen.c", 34
L0012:	lda     (sp),y
	sta     ptr1+1
	lda     (sp)
	sta     ptr1
	lda     (ptr1)
	ldx     #$00
	jsr     _close
	cpx     #$80
	bcc     L000A
;
; return 0;
;
	.dbg	line, "freopen.c", 36
	ldx     #$00
	txa
	jmp     incsp6
;
; return _fopen (name, mode, f);
;
	.dbg	line, "freopen.c", 40
L000A:	jsr     decsp4
	ldy     #$09
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$07
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     (sp)
	ldy     #$01
	txa
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     __fopen
;
; }
;
	.dbg	line, "freopen.c", 41
	jmp     incsp6
	.dbg	line

.endproc

