;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65816"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "fseek.c", 1389, 1084483758
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdio.h", 5951, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stddef.h", 2972, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdarg.h", 2817, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/errno.h", 4695, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/unistd.h", 4203, 1344797532
	.dbg		file, "_file.h", 742, 1084367796
	.dbg		sym, "_errno", "00", extern, "__errno"
	.dbg		sym, "lseek", "00", extern, "_lseek"
	.export		_fseek
	.import		__errno
	.import		_lseek

; ---------------------------------------------------------------
; int __near__ __fastcall__ fseek (register __near__ struct _FILE*, long, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fseek: near

	.dbg	func, "fseek", "00", extern, "_fseek"
	.dbg	sym, "f", "00", register, "regbank", 4
	.dbg	sym, "offset", "00", auto, 2
	.dbg	sym, "whence", "00", auto, 0
	.dbg	sym, "res", "00", auto, -4

.segment	"CODE"

;
; {
;
	.dbg	line, "fseek.c", 24
	jsr     pushax
	ldy     #$06
	ldx     #$04
	jsr     regswap2
;
; if ((f->f_flags & _FOPEN) == 0) {
;
	.dbg	line, "fseek.c", 28
	jsr     decsp4
	ldy     #$01
	lda     (regbank+4),y
	and     #$01
	bne     L0020
;
; _errno = EINVAL;                /* File not open */
;
	.dbg	line, "fseek.c", 29
	lda     #$07
	sta     __errno
	stz     __errno+1
;
; return -1;
;
	.dbg	line, "fseek.c", 30
	ldx     #$FF
	bra     L0024
;
; if ((f->f_flags & _FPUSHBACK) && whence == SEEK_CUR) {
;
	.dbg	line, "fseek.c", 36
L0020:	lda     (regbank+4),y
	and     #$08
	beq     L000A
	ldy     #$04
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L000A
;
; --offset;
;
	.dbg	line, "fseek.c", 37
	tax
	stz     sreg
	stz     sreg+1
	ina
	iny
	jsr     lsubeqysp
;
; res = lseek(f->f_fd, offset, whence);
;
	.dbg	line, "fseek.c", 41
L000A:	jsr     decsp6
	lda     (regbank+4)
	ldy     #$04
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	ldy     #$0F
	jsr     ldeaxysp
	jsr     steax0sp
	ldy     #$0B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _lseek
	jsr     steax0sp
;
; if (res < 0) {
;
	.dbg	line, "fseek.c", 47
	jsr     ldeax0sp
	lda     sreg+1
	asl     a
	bcc     L0016
;
; f->f_flags |= _FERROR;
;
	.dbg	line, "fseek.c", 48
	ldy     #$01
	lda     (regbank+4),y
	ora     #$04
	sta     (regbank+4),y
;
; return -1;
;
	.dbg	line, "fseek.c", 49
	ldx     #$FF
	bra     L0024
;
; f->f_flags &= ~(_FEOF | _FPUSHBACK);
;
	.dbg	line, "fseek.c", 55
L0016:	ldy     #$01
	lda     (regbank+4),y
	and     #$F5
	sta     (regbank+4),y
;
; return 0;
;
	.dbg	line, "fseek.c", 58
	ldx     #$00
L0024:	txa
;
; }
;
	.dbg	line, "fseek.c", 59
	pha
	ldy     #$0A
	lda     (sp),y
	sta     regbank+4
	iny
	lda     (sp),y
	sta     regbank+5
	pla
	iny
	jmp     addysp
	.dbg	line

.endproc

