;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65816"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "getchar.c", 400, 1344797853
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdio.h", 5951, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stddef.h", 2972, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdarg.h", 2817, 1344797532
	.dbg		sym, "stdin", "00", extern, "_stdin"
	.dbg		sym, "fgetc", "00", extern, "_fgetc"
	.import		_stdin
	.import		_fgetc
	.export		_getchar

; ---------------------------------------------------------------
; int __near__ getchar (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_getchar: near

	.dbg	func, "getchar", "00", extern, "_getchar"

.segment	"CODE"

;
; return fgetc (stdin);
;
	.dbg	line, "getchar.c", 22
	lda     _stdin
	ldx     _stdin+1
	jmp     _fgetc
	.dbg	line

.endproc

