;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65816"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "gets.c", 897, 1068141847
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdio.h", 5951, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stddef.h", 2972, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdarg.h", 2817, 1344797532
	.dbg		file, "_file.h", 742, 1084367796
	.dbg		sym, "stdin", "00", extern, "_stdin"
	.dbg		sym, "fgetc", "00", extern, "_fgetc"
	.import		_stdin
	.import		_fgetc
	.export		_gets

; ---------------------------------------------------------------
; __near__ unsigned char* __near__ __fastcall__ gets (__near__ unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_gets: near

	.dbg	func, "gets", "00", extern, "_gets"
	.dbg	sym, "s", "00", auto, 0
	.dbg	sym, "c", "00", auto, -2
	.dbg	sym, "i", "00", auto, -4

.segment	"CODE"

;
; {
;
	.dbg	line, "gets.c", 21
	jsr     pushax
;
; int i = 0;
;
	.dbg	line, "gets.c", 23
	jsr     decsp2
	jsr     push0
;
; if ((c = fgetc (stdin)) == EOF) {
;
	.dbg	line, "gets.c", 28
L0004:	lda     _stdin
	ldx     _stdin+1
	jsr     _fgetc
	ldy     #$02
	jsr     staxysp
	cpx     #$FF
	bne     L0017
	cmp     #$FF
	bne     L0017
;
; s [i] = 0;
;
	.dbg	line, "gets.c", 30
	ldy     #$04
	lda     (sp),y
	clc
	adc     (sp)
	sta     ptr1
	iny
	lda     (sp),y
	ldy     #$01
	adc     (sp),y
	sta     ptr1+1
	lda     #$00
	sta     (ptr1)
;
; if (stdin->f_flags & _FERROR) {
;
	.dbg	line, "gets.c", 31
	lda     _stdin
	sta     ptr1
	lda     _stdin+1
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	inx
	and     #$04
	beq     L0025
;
; return 0;
;
	.dbg	line, "gets.c", 33
	txa
	jmp     incsp6
;
; if (i) {
;
	.dbg	line, "gets.c", 36
L0025:	lda     (sp),y
	ora     (sp)
	beq     L0002
;
; return s;
;
	.dbg	line, "gets.c", 37
	bra     L0028
;
; s [i++] = c;
;
	.dbg	line, "gets.c", 45
L0017:	ldy     #$07
	jsr     pushwysp
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     regsave
	stx     regsave+1
	ina
	bne     L001B
	inx
L001B:	ldy     #$02
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (sp),y
	sta     (ptr1)
;
; } while (c != '\n');
;
	.dbg	line, "gets.c", 47
	iny
	lda     (sp),y
	bne     L0004
	dey
	lda     (sp),y
	cmp     #$0A
	jne     L0004
;
; s [i-1] = '\0';
;
	.dbg	line, "gets.c", 50
	dey
	lda     (sp),y
	tax
	lda     (sp)
	sec
	sbc     #$01
	bcs     L0021
	dex
L0021:	clc
	ldy     #$04
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	lda     #$00
	sta     (ptr1)
;
; return s;
;
	.dbg	line, "gets.c", 53
L0028:	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
;
; }
;
	.dbg	line, "gets.c", 54
L0002:	jmp     incsp6
	.dbg	line

.endproc

