;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65816"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "gmtime.c", 3145, 1037177805
	.dbg		file, "/Users/steven/bin/lib/cc65/include/time.h", 5015, 1344797532
	.dbg		sym, "_tz", "00", extern, "__tz"
	.dbg		sym, "localtime", "00", extern, "_localtime"
	.import		__tz
	.export		_gmtime
	.import		_localtime

; ---------------------------------------------------------------
; __near__ struct tm* __near__ __fastcall__ gmtime (__near__ const unsigned long*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_gmtime: near

	.dbg	func, "gmtime", "00", extern, "_gmtime"
	.dbg	sym, "timep", "00", auto, 0
	.dbg	sym, "t", "00", auto, -4

.segment	"CODE"

;
; {
;
	.dbg	line, "gmtime.c", 47
	jsr     pushax
;
; if (timep == 0) {
;
	.dbg	line, "gmtime.c", 51
	jsr     decsp4
	ldy     #$04
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L000C
;
; return 0;
;
	.dbg	line, "gmtime.c", 52
	tax
	jmp     incsp6
;
; t = *timep + _tz.timezone;
;
	.dbg	line, "gmtime.c", 56
L000C:	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     ldeaxi
	jsr     pusheax
	lda     __tz+1+3
	sta     sreg+1
	lda     __tz+1+2
	sta     sreg
	ldx     __tz+1+1
	lda     __tz+1
	jsr     tosaddeax
	jsr     steax0sp
;
; return localtime (&t);
;
	.dbg	line, "gmtime.c", 59
	lda     sp
	ldx     sp+1
	jsr     _localtime
;
; }
;
	.dbg	line, "gmtime.c", 60
	jmp     incsp6
	.dbg	line

.endproc

