;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65816"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "localtime.c", 3622, 1037177805
	.dbg		file, "/Users/steven/bin/lib/cc65/include/time.h", 5015, 1344797532
	.dbg		sym, "mktime", "00", extern, "_mktime"
	.export		_localtime
	.import		_mktime

; ---------------------------------------------------------------
; __near__ struct tm* __near__ __fastcall__ localtime (__near__ const unsigned long*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_localtime: near

	.dbg	func, "localtime", "00", extern, "_localtime"
	.dbg	sym, "timep", "00", auto, 0
	.dbg	sym, "t", "00", auto, -4

.segment	"BSS"

L0004:
	.res	18,$00

.segment	"CODE"

;
; {
;
	.dbg	line, "localtime.c", 47
	jsr     pushax
;
; if (timep == 0 || (long) (t = *timep) < 0) {
;
	.dbg	line, "localtime.c", 52
	jsr     decsp4
	ldy     #$04
	lda     (sp),y
	iny
	ora     (sp),y
	beq     L001E
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     ldeaxi
	jsr     steax0sp
	lda     sreg+1
	asl     a
	bcc     L0005
;
; return 0;
;
	.dbg	line, "localtime.c", 54
L001E:	ldx     #$00
	txa
	jmp     incsp6
;
; timebuf.tm_sec  = t % 3600;
;
	.dbg	line, "localtime.c", 61
L0005:	jsr     ldeax0sp
	jsr     pusheax
	ldx     #$0E
	lda     #$10
	jsr     tosumod0ax
	sta     L0004
	stx     L0004+1
;
; timebuf.tm_min  = 0;
;
	.dbg	line, "localtime.c", 62
	stz     L0004+2
	stz     L0004+2+1
;
; timebuf.tm_hour = (t / 3600) % 24;
;
	.dbg	line, "localtime.c", 63
	jsr     ldeax0sp
	jsr     pusheax
	ldx     #$0E
	lda     #$10
	jsr     tosudiv0ax
	jsr     pusheax
	ldx     #$00
	lda     #$18
	jsr     tosumod0ax
	sta     L0004+4
	stx     L0004+4+1
;
; timebuf.tm_mday = (t / (3600UL * 24UL)) + 1;
;
	.dbg	line, "localtime.c", 64
	jsr     ldeax0sp
	jsr     pusheax
	ldx     #$51
	lda     #$01
	sta     sreg
	stz     sreg+1
	lda     #$80
	jsr     tosudiveax
	ldy     #$01
	jsr     inceaxy
	sta     L0004+6
	stx     L0004+6+1
;
; timebuf.tm_mon  = 0;
;
	.dbg	line, "localtime.c", 65
	stz     L0004+8
	stz     L0004+8+1
;
; timebuf.tm_year = 70;       /* Base value is 1/1/1970 */
;
	.dbg	line, "localtime.c", 66
	lda     #$46
	sta     L0004+10
	stz     L0004+10+1
;
; mktime (&timebuf);
;
	.dbg	line, "localtime.c", 69
	lda     #<(L0004)
	ldx     #>(L0004)
	jsr     _mktime
;
; return &timebuf;
;
	.dbg	line, "localtime.c", 72
	lda     #<(L0004)
	ldx     #>(L0004)
;
; }
;
	.dbg	line, "localtime.c", 73
	jmp     incsp6
	.dbg	line

.endproc

