;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65816"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "perror.c", 2949, 1051217755
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdio.h", 5951, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stddef.h", 2972, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdarg.h", 2817, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/string.h", 4883, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/errno.h", 4695, 1344797532
	.dbg		sym, "stderr", "00", extern, "_stderr"
	.dbg		sym, "fprintf", "00", extern, "_fprintf"
	.dbg		sym, "strerror", "00", extern, "_strerror"
	.dbg		sym, "_errno", "00", extern, "__errno"
	.import		_stderr
	.import		_fprintf
	.export		_perror
	.import		_strerror
	.import		__errno

.segment	"RODATA"

L0008:
	.byte	$25,$73,$3A,$20,$25,$73,$0A,$00
L000F	:=	L0008+4

; ---------------------------------------------------------------
; void __near__ __fastcall__ perror (__near__ const unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_perror: near

	.dbg	func, "perror", "00", extern, "_perror"
	.dbg	sym, "msg", "00", auto, 0
	.dbg	sym, "errormsg", "00", auto, -2

.segment	"CODE"

;
; {
;
	.dbg	line, "perror.c", 43
	jsr     pushax
;
; const char* errormsg = strerror (errno);
;
	.dbg	line, "perror.c", 45
	lda     __errno
	ldx     __errno+1
	jsr     _strerror
	jsr     pushax
;
; if (msg) {
;
	.dbg	line, "perror.c", 48
	ldy     #$03
	lda     (sp),y
	dey
	ora     (sp),y
	beq     L0004
;
; fprintf (stderr, "%s: %s\n", msg, errormsg);
;
	.dbg	line, "perror.c", 49
	jsr     decsp4
	lda     _stderr
	sta     (sp),y
	iny
	lda     _stderr+1
	sta     (sp),y
	lda     #<(L0008)
	sta     (sp)
	ldy     #$01
	lda     #>(L0008)
	sta     (sp),y
	ldy     #$09
	jsr     pushwysp
	ldy     #$09
	jsr     pushwysp
	ldy     #$08
;
; } else {
;
	.dbg	line, "perror.c", 50
	bra     L0012
;
; fprintf (stderr, "%s\n", errormsg);
;
	.dbg	line, "perror.c", 51
L0004:	jsr     decsp4
	lda     _stderr
	sta     (sp),y
	iny
	lda     _stderr+1
	sta     (sp),y
	lda     #<(L000F)
	sta     (sp)
	ldy     #$01
	lda     #>(L000F)
	sta     (sp),y
	ldy     #$07
	jsr     pushwysp
	ldy     #$06
L0012:	jsr     _fprintf
;
; }
;
	.dbg	line, "perror.c", 53
	jmp     incsp4
	.dbg	line

.endproc

