;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65816"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "puts.c", 636, 1068141847
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdio.h", 5951, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stddef.h", 2972, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdarg.h", 2817, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/string.h", 4883, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/unistd.h", 4203, 1344797532
	.dbg		file, "_file.h", 742, 1084367796
	.dbg		sym, "stdout", "00", extern, "_stdout"
	.dbg		sym, "strlen", "00", extern, "_strlen"
	.dbg		sym, "write", "00", extern, "_write"
	.import		_stdout
	.export		_puts
	.import		_strlen
	.import		_write

; ---------------------------------------------------------------
; int __near__ __fastcall__ puts (__near__ const unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_puts: near

	.dbg	func, "puts", "00", extern, "_puts"
	.dbg	sym, "s", "00", auto, 0

.segment	"DATA"

L0003:
	.byte	$0A

.segment	"CODE"

;
; {
;
	.dbg	line, "puts.c", 23
	jsr     pushax
;
; if (write (stdout->f_fd, s, strlen (s)) < 0 ||
;
	.dbg	line, "puts.c", 27
	jsr     decsp4
	lda     _stdout
	sta     ptr1
	lda     _stdout+1
	sta     ptr1+1
	lda     (ptr1)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     (sp)
	ldy     #$01
	txa
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _strlen
	jsr     _write
	cpx     #$80
	bcs     L0013
;
; write (stdout->f_fd, &nl, 1)        < 0) {
;
	.dbg	line, "puts.c", 28
	jsr     decsp4
	lda     _stdout
	sta     ptr1
	lda     _stdout+1
	sta     ptr1+1
	lda     (ptr1)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #<(L0003)
	sta     (sp)
	ldy     #$01
	lda     #>(L0003)
	sta     (sp),y
	ldx     #$00
	tya
	jsr     _write
	cpx     #$80
	bcs     L0013
	ldx     #$00
	txa
	jmp     incsp2
;
; stdout->f_flags |= _FERROR;
;
	.dbg	line, "puts.c", 29
L0013:	lda     _stdout
	sta     ptr1
	lda     _stdout+1
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	ora     #$04
	sta     (ptr1),y
;
; return -1;
;
	.dbg	line, "puts.c", 30
	ldx     #$FF
	txa
	jmp     incsp2
	.dbg	line

.endproc

