;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65816"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "rewind.c", 377, 1068141847
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdio.h", 5951, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stddef.h", 2972, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdarg.h", 2817, 1344797532
	.dbg		sym, "clearerr", "00", extern, "_clearerr"
	.dbg		sym, "fseek", "00", extern, "_fseek"
	.import		_clearerr
	.import		_fseek
	.export		_rewind

; ---------------------------------------------------------------
; void __near__ __fastcall__ rewind (__near__ struct _FILE*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_rewind: near

	.dbg	func, "rewind", "00", extern, "_rewind"
	.dbg	sym, "f", "00", auto, 0

.segment	"CODE"

;
; {
;
	.dbg	line, "rewind.c", 20
	jsr     pushax
;
; fseek(f, 0L, SEEK_SET);
;
	.dbg	line, "rewind.c", 21
	jsr     decsp6
	ldy     #$07
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$04
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldx     #$00
	txa
	sta     (sp)
	ldy     #$01
	sta     (sp),y
	iny
	sta     (sp),y
	iny
	sta     (sp),y
	lda     #$02
	jsr     _fseek
;
; clearerr(f);
;
	.dbg	line, "rewind.c", 22
	ldy     #$01
	lda     (sp),y
	tax
	lda     (sp)
	jsr     _clearerr
;
; }
;
	.dbg	line, "rewind.c", 23
	jmp     incsp2
	.dbg	line

.endproc

