;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65816"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "strftime.c", 8008, 1037210916
	.dbg		file, "/Users/steven/bin/lib/cc65/include/string.h", 4883, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stddef.h", 2972, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdio.h", 5951, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdarg.h", 2817, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/time.h", 5015, 1344797532
	.dbg		sym, "strlen", "00", extern, "_strlen"
	.dbg		sym, "memcpy", "00", extern, "_memcpy"
	.dbg		sym, "sprintf", "00", extern, "_sprintf"
	.dbg		sym, "_tz", "00", extern, "__tz"
	.import		_strlen
	.import		_memcpy
	.import		_sprintf
	.import		__tz
	.export		_strftime

.segment	"RODATA"

L00E0:
	.byte	$25,$2E,$33,$73,$20,$25,$2E,$33,$73,$25,$33,$64,$20,$25,$30,$32
	.byte	$64,$3A,$25,$30,$32,$64,$3A,$25,$30,$32,$64,$20,$25,$64,$00
L006E:
	.byte	$25,$30,$34,$64,$2D,$25,$30,$32,$64,$2D,$25,$30,$32,$64,$00
L0119	:=	L006E+0
L0064:
	.byte	$25,$30,$32,$64,$2F,$25,$30,$32,$64,$2F,$25,$30,$32,$64,$00
L00B8:
	.byte	$25,$30,$32,$64,$3A,$25,$30,$32,$64,$3A,$25,$30,$32,$64,$00
L000D:
	.byte	$57,$65,$64,$6E,$65,$73,$64,$61,$79,$00
L0027:
	.byte	$53,$65,$70,$74,$65,$6D,$62,$65,$72,$00
L0019:
	.byte	$46,$65,$62,$72,$75,$61,$72,$79,$00
L0013:
	.byte	$53,$61,$74,$75,$72,$64,$61,$79,$00
L002B:
	.byte	$4E,$6F,$76,$65,$6D,$62,$65,$72,$00
L000F:
	.byte	$54,$68,$75,$72,$73,$64,$61,$79,$00
L002D:
	.byte	$44,$65,$63,$65,$6D,$62,$65,$72,$00
L0017:
	.byte	$4A,$61,$6E,$75,$61,$72,$79,$00
L0029:
	.byte	$4F,$63,$74,$6F,$62,$65,$72,$00
L000B:
	.byte	$54,$75,$65,$73,$64,$61,$79,$00
L0025:
	.byte	$41,$75,$67,$75,$73,$74,$00
L0011:
	.byte	$46,$72,$69,$64,$61,$79,$00
L0007:
	.byte	$53,$75,$6E,$64,$61,$79,$00
L0009:
	.byte	$4D,$6F,$6E,$64,$61,$79,$00
L001B:
	.byte	$4D,$61,$72,$63,$68,$00
L001D:
	.byte	$41,$70,$72,$69,$6C,$00
L007F	:=	L006E+10
L0086	:=	L006E+10
L0123	:=	L006E+10
L0021:
	.byte	$4A,$75,$6E,$65,$00
L0099	:=	L006E+10
L00A0	:=	L006E+10
L00A9	:=	L006E+10
L00FE	:=	L006E+10
L00F6:
	.byte	$25,$30,$33,$64,$00
L00D0:
	.byte	$25,$2E,$33,$73,$00
L00D8	:=	L00D0+0
L0078	:=	L006E+10
L00EF	:=	L006E+10
L0023:
	.byte	$4A,$75,$6C,$79,$00
L001F:
	.byte	$4D,$61,$79,$00
L00C1:
	.byte	$25,$34,$64,$00
L010B:
	.byte	$41,$4D,$00
L0112	:=	L00E0+28
L0092:
	.byte	$61,$6D,$00
L008F:
	.byte	$70,$6D,$00
L0108:
	.byte	$50,$4D,$00

; ---------------------------------------------------------------
; unsigned int __near__ __fastcall__ strftime (__near__ unsigned char*, unsigned int, __near__ const unsigned char*, __near__ const struct tm*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_strftime: near

	.dbg	func, "strftime", "00", extern, "_strftime"
	.dbg	sym, "buf", "00", auto, 6
	.dbg	sym, "bufsize", "00", auto, 4
	.dbg	sym, "format", "00", auto, 2
	.dbg	sym, "tm", "00", auto, 0

.segment	"DATA"

L0006:
	.addr	L0007
	.addr	L0009
	.addr	L000B
	.addr	L000D
	.addr	L000F
	.addr	L0011
	.addr	L0013
L0016:
	.addr	L0017
	.addr	L0019
	.addr	L001B
	.addr	L001D
	.addr	L001F
	.addr	L0021
	.addr	L0023
	.addr	L0025
	.addr	L0027
	.addr	L0029
	.addr	L002B
	.addr	L002D

.segment	"BSS"

L002F:
	.res	2,$00
L0030:
	.res	2,$00
L0031:
	.res	1,$00
L0033:
	.res	40,$00
L0034:
	.res	2,$00

.segment	"CODE"

;
; {
;
	.dbg	line, "strftime.c", 55
	jsr     pushax
;
; count = 0;
;
	.dbg	line, "strftime.c", 72
	stz     L002F
	stz     L002F+1
;
; if (count >= bufsize) {
;
	.dbg	line, "strftime.c", 74
L0037:	lda     L002F
	ldy     #$04
	cmp     (sp),y
	lda     L002F+1
	iny
	sbc     (sp),y
	bcc     L003B
;
; return 0;
;
	.dbg	line, "strftime.c", 76
	ldx     #$00
	txa
	jmp     incsp8
;
; if ((c = *format++) == '\0') {
;
	.dbg	line, "strftime.c", 78
L003B:	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     regsave
	stx     regsave+1
	ina
	bne     L0042
	inx
L0042:	ldy     #$02
	jsr     staxysp
	lda     (regsave)
	sta     L0031
	cmp     #$00
	bne     L013D
;
; *buf = '\0';
;
	.dbg	line, "strftime.c", 80
	ldy     #$07
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$00
	sta     (ptr1)
;
; return count;
;
	.dbg	line, "strftime.c", 81
	lda     L002F
	ldx     L002F+1
	jmp     incsp8
;
; if (c == '%') {
;
	.dbg	line, "strftime.c", 83
L013D:	lda     L0031
	cmp     #$25
	jne     L0046
;
; argptr = arg;
;
	.dbg	line, "strftime.c", 85
	lda     #<(L0033)
	sta     L0034
	lda     #>(L0033)
	sta     L0034+1
;
; switch (*format++) {
;
	.dbg	line, "strftime.c", 86
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     regsave
	stx     regsave+1
	ina
	bne     L004B
	inx
L004B:	ldy     #$02
	jsr     staxysp
	lda     (regsave)
;
; }
;
	.dbg	line, "strftime.c", 203
	cmp     #$25
	jeq     L013F
	cmp     #$41
	jeq     L0057
	cmp     #$42
	jeq     L005C
	cmp     #$44
	jeq     L0061
	cmp     #$46
	jeq     L006B
	cmp     #$48
	jeq     L0075
	cmp     #$49
	jeq     L007C
	cmp     #$4D
	jeq     L0083
	cmp     #$50
	jeq     L008A
	cmp     #$53
	jeq     L0096
	cmp     #$55
	jeq     L009D
	cmp     #$57
	jeq     L00A6
	cmp     #$58
	jeq     L00B5
	cmp     #$59
	jeq     L00BE
	cmp     #$5A
	jeq     L00C5
	cmp     #$61
	jeq     L00CD
	cmp     #$62
	jeq     L00D5
	cmp     #$63
	jeq     L00DD
	cmp     #$64
	jeq     L00EC
	cmp     #$6A
	jeq     L00F3
	cmp     #$6D
	jeq     L00FB
	cmp     #$70
	jeq     L0103
	cmp     #$77
	jeq     L010F
	cmp     #$78
	jeq     L0116
	cmp     #$79
	jeq     L0120
	jmp     L0140
;
; arg[0] = '%';
;
	.dbg	line, "strftime.c", 89
L013F:	sta     L0033
;
; arg[1] = '\0';
;
	.dbg	line, "strftime.c", 90
	stz     L0033+1
;
; break;
;
	.dbg	line, "strftime.c", 91
	jmp     L004D
;
; argptr = days[tm->tm_wday];
;
	.dbg	line, "strftime.c", 94
L0057:	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	lda     (sp)
	sta     ptr1
	ldy     #$0D
	lda     (ptr1),y
	sta     tmp1
	dey
	lda     (ptr1),y
	asl     a
	rol     tmp1
	clc
	adc     #<(L0006)
	sta     ptr1
	lda     tmp1
	adc     #>(L0006)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	sta     L0034+1
	lda     (ptr1)
	sta     L0034
;
; break;
;
	.dbg	line, "strftime.c", 95
	jmp     L004D
;
; argptr = months[tm->tm_mon];
;
	.dbg	line, "strftime.c", 98
L005C:	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	lda     (sp)
	sta     ptr1
	ldy     #$09
	lda     (ptr1),y
	sta     tmp1
	dey
	lda     (ptr1),y
	asl     a
	rol     tmp1
	clc
	adc     #<(L0016)
	sta     ptr1
	lda     tmp1
	adc     #>(L0016)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	sta     L0034+1
	lda     (ptr1)
	sta     L0034
;
; break;
;
	.dbg	line, "strftime.c", 99
	jmp     L004D
;
; sprintf (arg, "%02d/%02d/%02d", tm->tm_mon + 1,
;
	.dbg	line, "strftime.c", 102
L0061:	jsr     decsp4
	lda     #<(L0033)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0033)
	sta     (sp),y
	lda     #<(L0064)
	sta     (sp)
	ldy     #$01
	lda     #>(L0064)
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$09
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	ina
	bne     L0067
	inx
L0067:	jsr     pushax
;
; tm->tm_mday, tm->tm_year % 100);
;
	.dbg	line, "strftime.c", 103
	ldy     #$07
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	iny
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldy     #$09
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$0B
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldx     #$00
	lda     #$64
	jsr     tosmoda0
	jsr     pushax
	ldy     #$0A
	jsr     _sprintf
;
; break;
;
	.dbg	line, "strftime.c", 104
	jmp     L004D
;
; sprintf (arg, "%04d-%02d-%02d", tm->tm_year + 1900,
;
	.dbg	line, "strftime.c", 108
L006B:	jsr     decsp4
	lda     #<(L0033)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0033)
	sta     (sp),y
	lda     #<(L006E)
	sta     (sp)
	ldy     #$01
	lda     #>(L006E)
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$0B
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	clc
	adc     #$6C
	pha
	txa
	adc     #$07
	tax
	pla
	jsr     pushax
;
; tm->tm_mon + 1, tm->tm_mday);
;
	.dbg	line, "strftime.c", 109
	ldy     #$07
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$09
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	ina
	bne     L0072
	inx
L0072:	jsr     pushax
	ldy     #$09
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	dey
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldy     #$0A
	jsr     _sprintf
;
; break;
;
	.dbg	line, "strftime.c", 110
	jmp     L004D
;
; sprintf (arg, "%02d", tm->tm_hour);
;
	.dbg	line, "strftime.c", 113
L0075:	jsr     decsp4
	lda     #<(L0033)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0033)
	sta     (sp),y
	lda     #<(L0078)
	sta     (sp)
	ldy     #$01
	lda     #>(L0078)
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	iny
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldy     #$06
	jsr     _sprintf
;
; break;
;
	.dbg	line, "strftime.c", 114
	jmp     L004D
;
; sprintf (arg, "%02d", tm->tm_hour % 12);
;
	.dbg	line, "strftime.c", 117
L007C:	jsr     decsp4
	lda     #<(L0033)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0033)
	sta     (sp),y
	lda     #<(L007F)
	sta     (sp)
	ldy     #$01
	lda     #>(L007F)
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	iny
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldx     #$00
	lda     #$0C
	jsr     tosmoda0
	jsr     pushax
	ldy     #$06
	jsr     _sprintf
;
; break;
;
	.dbg	line, "strftime.c", 118
	jmp     L004D
;
; sprintf (arg, "%02d", tm->tm_min);
;
	.dbg	line, "strftime.c", 121
L0083:	jsr     decsp4
	lda     #<(L0033)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0033)
	sta     (sp),y
	lda     #<(L0086)
	sta     (sp)
	ldy     #$01
	lda     #>(L0086)
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	dey
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldy     #$06
	jsr     _sprintf
;
; break;
;
	.dbg	line, "strftime.c", 122
	jmp     L004D
;
; argptr = (tm->tm_hour >= 12)? "pm" : "am";
;
	.dbg	line, "strftime.c", 126
L008A:	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	lda     (sp)
	sta     ptr1
	ldy     #$05
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	cmp     #$0C
	txa
	sbc     #$00
	bvs     L008E
	eor     #$80
L008E:	bpl     L0090
	lda     #<(L008F)
	ldx     #>(L008F)
	bra     L0093
L0090:	lda     #<(L0092)
	ldx     #>(L0092)
L0093:	sta     L0034
	stx     L0034+1
;
; break;
;
	.dbg	line, "strftime.c", 127
	jmp     L004D
;
; sprintf (arg, "%02d", tm->tm_sec);
;
	.dbg	line, "strftime.c", 130
L0096:	jsr     decsp4
	lda     #<(L0033)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0033)
	sta     (sp),y
	lda     #<(L0099)
	sta     (sp)
	ldy     #$01
	lda     #>(L0099)
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	jsr     pushax
	ldy     #$06
	jsr     _sprintf
;
; break;
;
	.dbg	line, "strftime.c", 131
	jmp     L004D
;
; sprintf (arg, "%02d", (tm->tm_yday + 7 - tm->tm_wday) / 7);
;
	.dbg	line, "strftime.c", 134
L009D:	jsr     decsp4
	lda     #<(L0033)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0033)
	sta     (sp),y
	lda     #<(L00A0)
	sta     (sp)
	ldy     #$01
	lda     #>(L00A0)
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$0F
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	clc
	adc     #$07
	bcc     L00A4
	inx
L00A4:	jsr     pushax
	ldy     #$07
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$0D
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     tossubax
	jsr     pushax
	lda     #$07
	jsr     tosdiva0
	jsr     pushax
	ldy     #$06
	jsr     _sprintf
;
; break;
;
	.dbg	line, "strftime.c", 135
	jmp     L004D
;
; sprintf (arg, "%02d", 
;
	.dbg	line, "strftime.c", 138
L00A6:	jsr     decsp4
	lda     #<(L0033)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0033)
	sta     (sp),y
	lda     #<(L00A9)
	sta     (sp)
	ldy     #$01
	lda     #>(L00A9)
	sta     (sp),y
;
; (tm->tm_yday + 7 - (tm->tm_wday? tm->tm_wday - 1 : 6)) / 7);
;
	.dbg	line, "strftime.c", 139
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$0F
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	clc
	adc     #$07
	bcc     L00AD
	inx
L00AD:	jsr     pushax
	ldy     #$07
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$0C
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	beq     L00AF
	ldy     #$07
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$0D
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	sec
	sbc     #$01
	bcs     L00B2
	dex
	bra     L00B2
L00AF:	tax
	lda     #$06
L00B2:	jsr     tossubax
	jsr     pushax
	lda     #$07
	jsr     tosdiva0
	jsr     pushax
	ldy     #$06
	jsr     _sprintf
;
; break;
;
	.dbg	line, "strftime.c", 140
	jmp     L004D
;
; sprintf (arg, "%02d:%02d:%02d", tm->tm_hour,
;
	.dbg	line, "strftime.c", 143
L00B5:	jsr     decsp4
	lda     #<(L0033)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0033)
	sta     (sp),y
	lda     #<(L00B8)
	sta     (sp)
	ldy     #$01
	lda     #>(L00B8)
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	iny
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
;
; tm->tm_min, tm->tm_sec);
;
	.dbg	line, "strftime.c", 144
	ldy     #$07
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$03
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldy     #$09
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	jsr     pushax
	ldy     #$0A
	jsr     _sprintf
;
; break;
;
	.dbg	line, "strftime.c", 145
	jmp     L004D
;
; sprintf (arg, "%4d", tm->tm_year + 1900);
;
	.dbg	line, "strftime.c", 148
L00BE:	jsr     decsp4
	lda     #<(L0033)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0033)
	sta     (sp),y
	lda     #<(L00C1)
	sta     (sp)
	ldy     #$01
	lda     #>(L00C1)
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$0B
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	clc
	adc     #$6C
	pha
	txa
	adc     #$07
	tax
	pla
	jsr     pushax
	ldy     #$06
	jsr     _sprintf
;
; break;
;
	.dbg	line, "strftime.c", 149
	jmp     L004D
;
; argptr = tm->tm_isdst? _tz.dstname : _tz.tzname;
;
	.dbg	line, "strftime.c", 152
L00C5:	ldy     #$01
	lda     (sp),y
	tax
	lda     (sp)
	ldy     #$10
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	beq     L00C8
	lda     #<(__tz+10)
	ldx     #>(__tz+10)
	bra     L00CA
L00C8:	lda     #<(__tz+5)
	ldx     #>(__tz+5)
L00CA:	sta     L0034
	stx     L0034+1
;
; break;
;
	.dbg	line, "strftime.c", 153
	jmp     L004D
;
; sprintf (arg, "%.3s", days[tm->tm_wday]);
;
	.dbg	line, "strftime.c", 156
L00CD:	jsr     decsp4
	lda     #<(L0033)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0033)
	sta     (sp),y
	lda     #<(L00D0)
	sta     (sp)
	ldy     #$01
	lda     #>(L00D0)
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$0D
	lda     (ptr1),y
	sta     tmp1
	dey
	lda     (ptr1),y
	asl     a
	rol     tmp1
	clc
	adc     #<(L0006)
	sta     ptr1
	lda     tmp1
	adc     #>(L0006)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	jsr     pushax
	ldy     #$06
	jsr     _sprintf
;
; break;
;
	.dbg	line, "strftime.c", 157
	jmp     L004D
;
; sprintf (arg, "%.3s", months[tm->tm_mon]);
;
	.dbg	line, "strftime.c", 160
L00D5:	jsr     decsp4
	lda     #<(L0033)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0033)
	sta     (sp),y
	lda     #<(L00D8)
	sta     (sp)
	ldy     #$01
	lda     #>(L00D8)
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$09
	lda     (ptr1),y
	sta     tmp1
	dey
	lda     (ptr1),y
	asl     a
	rol     tmp1
	clc
	adc     #<(L0016)
	sta     ptr1
	lda     tmp1
	adc     #>(L0016)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	jsr     pushax
	ldy     #$06
	jsr     _sprintf
;
; break;
;
	.dbg	line, "strftime.c", 161
	jmp     L004D
;
; sprintf (arg, "%.3s %.3s%3d %02d:%02d:%02d %d",
;
	.dbg	line, "strftime.c", 164
L00DD:	jsr     decsp4
	lda     #<(L0033)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0033)
	sta     (sp),y
	lda     #<(L00E0)
	sta     (sp)
	ldy     #$01
	lda     #>(L00E0)
	sta     (sp),y
;
; days[tm->tm_wday], months[tm->tm_mon],
;
	.dbg	line, "strftime.c", 165
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$0D
	lda     (ptr1),y
	sta     tmp1
	dey
	lda     (ptr1),y
	asl     a
	rol     tmp1
	clc
	adc     #<(L0006)
	sta     ptr1
	lda     tmp1
	adc     #>(L0006)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	jsr     pushax
	ldy     #$07
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$09
	lda     (ptr1),y
	sta     tmp1
	dey
	lda     (ptr1),y
	asl     a
	rol     tmp1
	clc
	adc     #<(L0016)
	sta     ptr1
	lda     tmp1
	adc     #>(L0016)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	jsr     pushax
;
; tm->tm_mday, tm->tm_hour, tm->tm_min,
;
	.dbg	line, "strftime.c", 166
	ldy     #$09
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	dey
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldy     #$0B
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$05
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldy     #$0D
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$03
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
;
; tm->tm_sec, tm->tm_year + 1900);
;
	.dbg	line, "strftime.c", 167
	ldy     #$0F
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$01
	lda     (ptr1),y
	tax
	lda     (ptr1)
	jsr     pushax
	ldy     #$11
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$0B
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	clc
	adc     #$6C
	pha
	txa
	adc     #$07
	tax
	pla
	jsr     pushax
	ldy     #$12
	jsr     _sprintf
;
; break;
;
	.dbg	line, "strftime.c", 168
	jmp     L004D
;
; sprintf (arg, "%02d", tm->tm_mday);
;
	.dbg	line, "strftime.c", 171
L00EC:	jsr     decsp4
	lda     #<(L0033)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0033)
	sta     (sp),y
	lda     #<(L00EF)
	sta     (sp)
	ldy     #$01
	lda     #>(L00EF)
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$07
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldy     #$06
	jsr     _sprintf
;
; break;
;
	.dbg	line, "strftime.c", 172
	jmp     L004D
;
; sprintf (arg, "%03d", tm->tm_yday + 1);
;
	.dbg	line, "strftime.c", 175
L00F3:	jsr     decsp4
	lda     #<(L0033)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0033)
	sta     (sp),y
	lda     #<(L00F6)
	sta     (sp)
	ldy     #$01
	lda     #>(L00F6)
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$0F
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	ina
	bne     L00F9
	inx
L00F9:	jsr     pushax
	ldy     #$06
	jsr     _sprintf
;
; break;
;
	.dbg	line, "strftime.c", 176
	jmp     L004D
;
; sprintf (arg, "%02d", tm->tm_mon + 1);
;
	.dbg	line, "strftime.c", 179
L00FB:	jsr     decsp4
	lda     #<(L0033)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0033)
	sta     (sp),y
	lda     #<(L00FE)
	sta     (sp)
	ldy     #$01
	lda     #>(L00FE)
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$09
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	ina
	bne     L0101
	inx
L0101:	jsr     pushax
	ldy     #$06
	jsr     _sprintf
;
; break;
;
	.dbg	line, "strftime.c", 180
	jmp     L004D
;
; argptr = (tm->tm_hour >= 12)? "PM" : "AM";
;
	.dbg	line, "strftime.c", 183
L0103:	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	lda     (sp)
	sta     ptr1
	ldy     #$05
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	cmp     #$0C
	txa
	sbc     #$00
	bvs     L0107
	eor     #$80
L0107:	bpl     L0109
	lda     #<(L0108)
	ldx     #>(L0108)
	bra     L010C
L0109:	lda     #<(L010B)
	ldx     #>(L010B)
L010C:	sta     L0034
	stx     L0034+1
;
; break;
;
	.dbg	line, "strftime.c", 184
	jmp     L004D
;
; sprintf (arg, "%d", tm->tm_wday);
;
	.dbg	line, "strftime.c", 187
L010F:	jsr     decsp4
	lda     #<(L0033)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0033)
	sta     (sp),y
	lda     #<(L0112)
	sta     (sp)
	ldy     #$01
	lda     #>(L0112)
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$0D
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldy     #$06
	jsr     _sprintf
;
; break;
;
	.dbg	line, "strftime.c", 188
	jmp     L004D
;
; sprintf (arg, "%04d-%02d-%02d", tm->tm_year + 1900,
;
	.dbg	line, "strftime.c", 191
L0116:	jsr     decsp4
	lda     #<(L0033)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0033)
	sta     (sp),y
	lda     #<(L0119)
	sta     (sp)
	ldy     #$01
	lda     #>(L0119)
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$0B
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	clc
	adc     #$6C
	pha
	txa
	adc     #$07
	tax
	pla
	jsr     pushax
;
; tm->tm_mon + 1, tm->tm_mday);
;
	.dbg	line, "strftime.c", 192
	ldy     #$07
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$09
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	ina
	bne     L011D
	inx
L011D:	jsr     pushax
	ldy     #$09
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	dey
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldy     #$0A
	jsr     _sprintf
;
; break;
;
	.dbg	line, "strftime.c", 193
	bra     L004D
;
; sprintf (arg, "%02d", tm->tm_year % 100);
;
	.dbg	line, "strftime.c", 196
L0120:	jsr     decsp4
	lda     #<(L0033)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0033)
	sta     (sp),y
	lda     #<(L0123)
	sta     (sp)
	ldy     #$01
	lda     #>(L0123)
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$0B
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldx     #$00
	lda     #$64
	jsr     tosmoda0
	jsr     pushax
	ldy     #$06
	jsr     _sprintf
;
; break;
;
	.dbg	line, "strftime.c", 197
	bra     L004D
;
; arg[0] = '\0';
;
	.dbg	line, "strftime.c", 201
L0140:	stz     L0033
;
; len = strlen (argptr);
;
	.dbg	line, "strftime.c", 206
L004D:	lda     L0034
	ldx     L0034+1
	jsr     _strlen
	sta     L0030
	stx     L0030+1
;
; count += len;
;
	.dbg	line, "strftime.c", 207
	clc
	adc     L002F
	sta     L002F
	txa
	adc     L002F+1
	sta     L002F+1
;
; if (count < bufsize) {
;
	.dbg	line, "strftime.c", 208
	lda     L002F
	ldy     #$04
	cmp     (sp),y
	lda     L002F+1
	iny
	sbc     (sp),y
	jcs     L0037
;
; memcpy (buf, argptr, len);
;
	.dbg	line, "strftime.c", 209
	ldy     #$09
	jsr     pushwysp
	lda     L0034
	ldx     L0034+1
	jsr     pushax
	lda     L0030
	ldx     L0030+1
	jsr     _memcpy
;
; buf += len;
;
	.dbg	line, "strftime.c", 210
	lda     L0030
	ldx     L0030+1
	ldy     #$06
	jsr     addeqysp
;
; } else {
;
	.dbg	line, "strftime.c", 213
	jmp     L0037
;
; *buf++ = c;
;
	.dbg	line, "strftime.c", 216
L0046:	ldy     #$07
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     regsave
	stx     regsave+1
	ina
	bne     L0139
	inx
L0139:	ldy     #$06
	jsr     staxysp
	lda     L0031
	sta     (regsave)
;
; ++count;
;
	.dbg	line, "strftime.c", 217
	inc     L002F
	jne     L0037
	inc     L002F+1
;
; while (1) {
;
	.dbg	line, "strftime.c", 73
	jmp     L0037
	.dbg	line

.endproc

