;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65816"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "system.c", 317, 1253048480
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdio.h", 5951, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stddef.h", 2972, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdarg.h", 2817, 1344797532
	.dbg		file, "/Users/steven/bin/lib/cc65/include/stdlib.h", 5606, 1344797532
	.export		_system

; ---------------------------------------------------------------
; int __near__ __fastcall__ system (__near__ const unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_system: near

	.dbg	func, "system", "00", extern, "_system"
	.dbg	sym, "s", "00", auto, 0

.segment	"CODE"

;
; {
;
	.dbg	line, "system.c", 12
	jsr     pushax
;
; if (s == NULL) {
;
	.dbg	line, "system.c", 13
	lda     (sp)
	ldy     #$01
	ora     (sp),y
	bne     L0002
;
; return 0;               /* no shell */
;
	.dbg	line, "system.c", 14
	tax
	jmp     incsp2
;
; return -1;              /* always fail */
;
	.dbg	line, "system.c", 16
L0002:	ldx     #$FF
	txa
;
; }
;
	.dbg	line, "system.c", 18
	jmp     incsp2
	.dbg	line

.endproc

